dist: xenial-xerus
language: cpp
compiler:
  - gcc-4.8
before_script:
  - sudo apt-get install  -y gcc-4.8 g++-4.8 libopencv-dev libboost1.55-all-dev cmake
  - wget https://download.affectiva.com/linux/https://download.affectiva.com/linux/affdex-cpp-sdk-3.3-40-ubuntu-xenial-xerus-x86_64bit.tar.gz -O /tmp/affdex-sdk.tar.gz
  - mkdir /tmp/affdex-sdk
  - tar -xzvf /tmp/affdex-sdk.tar.gz -C /tmp/affdex-sdk
  - mkdir build
  - cd build
  - cmake -DBOOST_ROOT=/usr/ -DOpenCV_DIR=/usr/ -DAFFDEX_DIR=/tmp/affdex-sdk ..
script:
  - make
