version: 1.0.{build}
image:
- Visual Studio 2013
- Visual Studio 2015
configuration: Release
platform: x64
before_build:
- cmd: >-
    appveyor DownloadFile https://download.affectiva.com/windows/AffdexSDK-4.0.0-615-win64.exe -FileName AffdexSDK-win64.exe

    AffdexSDK-win64.exe /S

    nuget restore affdex-win-samples.sln

build:
  project: affdex-win-samples.sln
  parallel: true
  verbosity: detailed
artifacts:
- path: 'x64\Release'
deploy:
- provider: GitHub
  release: 4.0
  artifact: 'x64\Release.zip'
  auth_token:
    secure: sjCE8t4b8ME8j2D6e0kRpNib8STOljgGVPdexj4n0gXU/nYxFkdaI9GXRukRHri5
  on:
    branch: master                 # release from master branch only
